//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep_BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public long Id { get; set; }
        public long Branches_Code { get; set; }
        public string Branches_Name { get; set; }
        public int IsDeleted { get; set; }
        public long Warhouse_Code { get; set; }
    }
}
