//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep_BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Type_Back_Office
    {
        public int Id_Back_Office { get; set; }
        public string Operation_Type_Name { get; set; }
    }
}
