//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep_BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int Id { get; set; }
        public long ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public bool isActive { get; set; }
        public string ImageUrl { get; set; }
    }
}
