//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_View
    {
        public string SexTypeName { get; set; }
        public string Branches_Name { get; set; }
        public string JobName { get; set; }
        public long Employee_Code { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_National_Id { get; set; }
        public string Employee_Mobile_1 { get; set; }
        public string Employee_Address { get; set; }
        public string Employee_Mobile_2 { get; set; }
        public string Employee_Email { get; set; }
        public long Branch_ID { get; set; }
        public Nullable<System.DateTime> Employee_Start_Jop { get; set; }
        public Nullable<System.DateTime> Employee_End_Jop { get; set; }
        public string Employee_Notes { get; set; }
        public int IsDeleted { get; set; }
        public int SexTypeCode { get; set; }
        public long Jop_Code { get; set; }
    }
}
