//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_History
    {
        public long Id { get; set; }
        public long Item_Id { get; set; }
        public double Qty { get; set; }
        public double Price_Buy { get; set; }
        public double Price_Sale { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsFinshed { get; set; }
        public long Sale_Master_Code { get; set; }
        public bool Is_Used { get; set; }
        public double Current_Qty_Now { get; set; }
    }
}
