//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
 
    using System.Data.Objects.DataClasses;
    using System.Linq;
    using System.Data.Entity.Core.Objects;

    public partial class PointOfSaleEntities2 : DbContext
    {
        public PointOfSaleEntities2()
            : base("name=PointOfSaleEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer_Info> Customer_Info { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<ExpensesTransaction> ExpensesTransactions { get; set; }
        public DbSet<Item_History> Item_History { get; set; }
        public DbSet<Item_History_transaction> Item_History_transaction { get; set; }
        public DbSet<ItemCard> ItemCards { get; set; }
        public DbSet<Jop> Jops { get; set; }
        public DbSet<SaleDetail> SaleDetails { get; set; }
        public DbSet<SaleMaster> SaleMasters { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<SexType> SexTypes { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<Tab_Info> Tab_Info { get; set; }
        public DbSet<UnitCard> UnitCards { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_Auth> User_Auth { get; set; }
        public DbSet<UserEvent> UserEvents { get; set; }
        public DbSet<Operation_Type> Operation_Type { get; set; }
        public DbSet<Payment_Type> Payment_Type { get; set; }
        public DbSet<Auth_View> Auth_View { get; set; }
        public DbSet<Customer_View> Customer_View { get; set; }
        public DbSet<Employee_View> Employee_View { get; set; }
        public DbSet<ExpensesView> ExpensesViews { get; set; }
        public DbSet<ItemCardView> ItemCardViews { get; set; }
        public DbSet<SaleDetailView> SaleDetailViews { get; set; }
        public DbSet<SaleMasterView> SaleMasterViews { get; set; }
        public DbSet<Shift_View> Shift_View { get; set; }
        public DbSet<User_View> User_View { get; set; }
    
        public virtual int Delete_Trancation_By_User_Code(Nullable<long> user_Code, ObjectParameter message)
        {
            var user_CodeParameter = user_Code.HasValue ?
                new ObjectParameter("User_Code", user_Code) :
                new ObjectParameter("User_Code", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Trancation_By_User_Code", user_CodeParameter, message);
        }
    
        public virtual int TruncateTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateTables");
        }
    }
}
