//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppActivation
    {
        public int id { get; set; }
        public bool ActivaionState { get; set; }
        public string AdminUserName { get; set; }
        public string AdminPassowrd { get; set; }
        public int IsDeleted { get; set; }
        public string AppVersion { get; set; }
        public long BranchId { get; set; }
        public string CPU_Code { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public int Login_Offline_Count { get; set; }
    }
}
