//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_View
    {
        public string Tab_Name { get; set; }
        public int Tab_IsDeleted { get; set; }
        public int User_IsDeleted { get; set; }
        public long User_Code { get; set; }
        public long Auth_Code { get; set; }
        public long Tab_Info_Code { get; set; }
        public long Id { get; set; }
        public string Tab_Description_Eng { get; set; }
        public long Branch_Code { get; set; }
        public bool is_Back_Office_Updated { get; set; }
    }
}
