//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOfficeTranDetail_View
    {
        public string Branches_Name { get; set; }
        public string Event_Name { get; set; }
        public string Table_Name { get; set; }
        public bool Is_Brach_Take_Update { get; set; }
        public string Fail_Take_Update_Reason { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int IsDeleted { get; set; }
        public long Id { get; set; }
    }
}
