//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTransaction
    {
        public int Id { get; set; }
        public long ExpensesCode { get; set; }
        public double ExpensesQT { get; set; }
        public string ExpensesNotes { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> Last_Modified_By { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public int IsDeleted { get; set; }
        public long Shift_Code { get; set; }
    }
}
