//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCardView
    {
        public long ItemCode { get; set; }
        public string CategoryName { get; set; }
        public string UnitName { get; set; }
        public string ParCode { get; set; }
        public double Price { get; set; }
        public string Name { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<bool> AddItem { get; set; }
        public long CategoryCode { get; set; }
        public long UnitCode { get; set; }
        public double PriceBuy { get; set; }
        public Nullable<double> Item_Risk_limit { get; set; }
        public double Item_Count_InStoreg { get; set; }
    }
}
