//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public long id { get; set; }
        public long Item_Code { get; set; }
        public long From_WareHouse_Code { get; set; }
        public long To_WareHouseCode { get; set; }
        public int PO_Request_State { get; set; }
        public int IsDeleted { get; set; }
        public double PO_Item_Qty { get; set; }
        public long Creted_By_User { get; set; }
        public System.DateTime Created_Date { get; set; }
        public long Warehouse_Transaction_Code { get; set; }
        public string Reason { get; set; }
    }
}
