//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POSEntity : DbContext
    {
        public POSEntity()
            : base("name=POSEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Back_Office_Transaction_Detail> Back_Office_Transaction_Detail { get; set; }
        public virtual DbSet<Back_Office_Transaction_Master> Back_Office_Transaction_Master { get; set; }
        public virtual DbSet<Branch_Back_Office> Branch_Back_Office { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Back_Office> Category_Back_Office { get; set; }
        public virtual DbSet<Customer_Info> Customer_Info { get; set; }
        public virtual DbSet<Customer_Info_Back_Office> Customer_Info_Back_Office { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Back_Office> Employee_Back_Office { get; set; }
        public virtual DbSet<Event_Type> Event_Type { get; set; }
        public virtual DbSet<Event_Type_Back_Office> Event_Type_Back_Office { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Expenses_Back_Office> Expenses_Back_Office { get; set; }
        public virtual DbSet<ExpensesTransaction> ExpensesTransactions { get; set; }
        public virtual DbSet<ExpensesTransaction_Back_Office> ExpensesTransaction_Back_Office { get; set; }
        public virtual DbSet<Item_Balance> Item_Balance { get; set; }
        public virtual DbSet<Item_History> Item_History { get; set; }
        public virtual DbSet<Item_History_Back_Office> Item_History_Back_Office { get; set; }
        public virtual DbSet<Item_History_transaction> Item_History_transaction { get; set; }
        public virtual DbSet<Item_History_transaction_Back_Office> Item_History_transaction_Back_Office { get; set; }
        public virtual DbSet<ItemCard> ItemCards { get; set; }
        public virtual DbSet<ItemCard_Back_Office> ItemCard_Back_Office { get; set; }
        public virtual DbSet<Jop> Jops { get; set; }
        public virtual DbSet<Jops_Back_Office> Jops_Back_Office { get; set; }
        public virtual DbSet<Operation_Type> Operation_Type { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<Project_Tables> Project_Tables { get; set; }
        public virtual DbSet<Project_Tables_Back_Office> Project_Tables_Back_Office { get; set; }
        public virtual DbSet<ProjectMangerInfo> ProjectMangerInfoes { get; set; }
        public virtual DbSet<ProjectMangerInfo_Back_Office> ProjectMangerInfo_Back_Office { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<SaleDetail_Back_Office> SaleDetail_Back_Office { get; set; }
        public virtual DbSet<SaleMaster> SaleMasters { get; set; }
        public virtual DbSet<SaleMaster_Back_Office> SaleMaster_Back_Office { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Sales_Back_Office> Sales_Back_Office { get; set; }
        public virtual DbSet<SexType> SexTypes { get; set; }
        public virtual DbSet<SexType_Back_Office> SexType_Back_Office { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Shift_Back_Office> Shift_Back_Office { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Tab_Info> Tab_Info { get; set; }
        public virtual DbSet<Tab_Info_Back_Office> Tab_Info_Back_Office { get; set; }
        public virtual DbSet<UnitCard> UnitCards { get; set; }
        public virtual DbSet<UnitCard_Back_Office> UnitCard_Back_Office { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Auth> User_Auth { get; set; }
        public virtual DbSet<User_Auth_Back_Office> User_Auth_Back_Office { get; set; }
        public virtual DbSet<User_Back_Office> User_Back_Office { get; set; }
        public virtual DbSet<UserEvent> UserEvents { get; set; }
        public virtual DbSet<UserEvents_Back_Office> UserEvents_Back_Office { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Warehouse_Back_Office> Warehouse_Back_Office { get; set; }
        public virtual DbSet<Warehouse_Transaction> Warehouse_Transaction { get; set; }
        public virtual DbSet<Warehouse_Transaction_Back_Office> Warehouse_Transaction_Back_Office { get; set; }
        public virtual DbSet<Operation_Type_Back_Office> Operation_Type_Back_Office { get; set; }
        public virtual DbSet<Payment_Type_Back_Office> Payment_Type_Back_Office { get; set; }
        public virtual DbSet<ProjectInfo> ProjectInfoes { get; set; }
        public virtual DbSet<ProjectInfo_Back_Office> ProjectInfo_Back_Office { get; set; }
        public virtual DbSet<Auth_View> Auth_View { get; set; }
        public virtual DbSet<BackOfficeTranDetail_View> BackOfficeTranDetail_View { get; set; }
        public virtual DbSet<Customer_View> Customer_View { get; set; }
        public virtual DbSet<Employee_View> Employee_View { get; set; }
        public virtual DbSet<ExpensesView> ExpensesViews { get; set; }
        public virtual DbSet<ItemCardView> ItemCardViews { get; set; }
        public virtual DbSet<PO_View> PO_View { get; set; }
        public virtual DbSet<SaleDetailView> SaleDetailViews { get; set; }
        public virtual DbSet<SaleMasterView> SaleMasterViews { get; set; }
        public virtual DbSet<Shift_View> Shift_View { get; set; }
        public virtual DbSet<User_View> User_View { get; set; }
        public virtual DbSet<warhouse_view> warhouse_view { get; set; }
    
        public virtual int Delete_Trancation_By_User_Code(Nullable<long> user_Code, Nullable<long> branch_Code, ObjectParameter message)
        {
            var user_CodeParameter = user_Code.HasValue ?
                new ObjectParameter("User_Code", user_Code) :
                new ObjectParameter("User_Code", typeof(long));
    
            var branch_CodeParameter = branch_Code.HasValue ?
                new ObjectParameter("Branch_Code", branch_Code) :
                new ObjectParameter("Branch_Code", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Trancation_By_User_Code", user_CodeParameter, branch_CodeParameter, message);
        }
    
        public virtual int TruncateTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateTables");
        }
    }
}
