//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public long Id { get; set; }
        public long SaleMasterCode { get; set; }
        public long SaleDetailCode { get; set; }
        public long ItemCode { get; set; }
        public double Price { get; set; }
        public double Qty { get; set; }
        public double Total { get; set; }
        public System.DateTime EntryDate { get; set; }
        public long UserId { get; set; }
        public int IsDeleted { get; set; }
        public long Operation_Type_Id { get; set; }
        public Nullable<System.DateTime> LastDateModif { get; set; }
        public long CustomerCode { get; set; }
        public long shiftCode { get; set; }
    }
}
