//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Back_Office
    {
        public long Id { get; set; }
        public long Sales_Code_Back_Office { get; set; }
        public string Sales_Name { get; set; }
        public string Sales_Phone { get; set; }
        public string Sales_Address { get; set; }
        public string Sales_NationalID { get; set; }
        public string Sales_Email { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public long Last_Modified_User { get; set; }
        public int IsDeleted { get; set; }
        public bool is_Back_Office_Updated { get; set; }
        public long Back_Office_Master_Code { get; set; }
        public long Back_Office_Detail_Code { get; set; }
    }
}
