//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int id { get; set; }
        public int State_Code { get; set; }
        public string State_Name { get; set; }
        public int IsDeleted { get; set; }
    }
}
