//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_View
    {
        public string Branches_Name { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<long> Employee_Code { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<int> IsDeletedEmployee { get; set; }
        public bool UserFlag { get; set; }
        public string Warehouse_Name { get; set; }
        public long Warehouse_Code { get; set; }
        public long Branches_Code { get; set; }
    }
}
