//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_History_Back_Office
    {
        public long Id_Back_Office { get; set; }
        public long Warhouse_Transfer_Code { get; set; }
        public long From_Branch_Id { get; set; }
        public long From_Warhouse_Code { get; set; }
        public long Item_Id { get; set; }
        public double Qty { get; set; }
        public double Price_Buy { get; set; }
        public long To_Warhouse_Code { get; set; }
        public long To_Branch_Code { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Is_Branch_Take_Update { get; set; }
        public int IsDeleted { get; set; }
        public long Main_Master_Code { get; set; }
        public long Main_Item_History_Code { get; set; }
        public long PO_Code { get; set; }
    }
}
