//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jop
    {
        public long Id { get; set; }
        public long JopCode { get; set; }
        public string JobName { get; set; }
        public int IsDeleted { get; set; }
        public long Branch_Code { get; set; }
        public bool is_Back_Office_Updated { get; set; }
    }
}
