//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_View
    {
        public long Employee_Code { get; set; }
        public string Employee_Name { get; set; }
        public string State_Name { get; set; }
        public int State_Code { get; set; }
        public double PO_Item_Qty { get; set; }
        public System.DateTime Created_Date { get; set; }
        public long To_WareHouseCode { get; set; }
        public long From_WareHouse_Code { get; set; }
        public long id { get; set; }
        public long Warehouse_Transaction_Code { get; set; }
        public string Reason { get; set; }
        public string To_Warehouse { get; set; }
        public string From_Warehouse { get; set; }
    }
}
