//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetailView
    {
        public long ItemCode { get; set; }
        public Nullable<long> CategoryCode { get; set; }
        public string ParCode { get; set; }
        public string Name { get; set; }
        public double Qty { get; set; }
        public double Total { get; set; }
        public System.DateTime EntryDate { get; set; }
        public double Price { get; set; }
        public int IsDeleted { get; set; }
        public string UnitName { get; set; }
        public Nullable<long> UnitCode { get; set; }
        public long SaleMasterCode { get; set; }
        public long Operation_Type_Id { get; set; }
        public double PriceBuy { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> AddItem { get; set; }
        public double Item_Count_InStoreg { get; set; }
        public string UserName { get; set; }
        public long Emp_Code { get; set; }
        public long Id { get; set; }
        public long CustomerCode { get; set; }
        public long shiftCode { get; set; }
        public long LineSequence { get; set; }
        public bool isOile { get; set; }
        public string Name_En { get; set; }
        public long Warhouse_Code { get; set; }
        public string Warehouse_Name { get; set; }
        public double Item_DisCount { get; set; }
        public long Branches_Code { get; set; }
    }
}
