//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Auth
    {
        public long Id { get; set; }
        public long Auth_Code { get; set; }
        public long User_Code { get; set; }
        public long Tab_Info_Code { get; set; }
        public bool InActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<long> Last_Modified_User { get; set; }
        public int IsDeleted { get; set; }
        public long Branch_Code { get; set; }
        public bool is_Back_Office_Updated { get; set; }
    }
}
